// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaWGT8VllVaNG4NcEeGyrNAY0OD9lhIJs',
    appId: '1:94237990307:web:1add09d14f5794bca44e16',
    messagingSenderId: '94237990307',
    projectId: 'rapid-report-bdfe6',
    authDomain: 'rapid-report-bdfe6.firebaseapp.com',
    storageBucket: 'rapid-report-bdfe6.firebasestorage.app',
    measurementId: 'G-JQ06MC5CY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4PJbzInp-e01Qh2zaBGuCs0y6nE2FT9g',
    appId: '1:94237990307:android:b9ab57ec8fb79fafa44e16',
    messagingSenderId: '94237990307',
    projectId: 'rapid-report-bdfe6',
    storageBucket: 'rapid-report-bdfe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnF8erMb8IPi-hRCBqJFpbRED1mnLIEc',
    appId: '1:94237990307:ios:c973515fc7fd78eea44e16',
    messagingSenderId: '94237990307',
    projectId: 'rapid-report-bdfe6',
    storageBucket: 'rapid-report-bdfe6.firebasestorage.app',
    iosBundleId: 'com.example.incidentResposneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGnF8erMb8IPi-hRCBqJFpbRED1mnLIEc',
    appId: '1:94237990307:ios:c973515fc7fd78eea44e16',
    messagingSenderId: '94237990307',
    projectId: 'rapid-report-bdfe6',
    storageBucket: 'rapid-report-bdfe6.firebasestorage.app',
    iosBundleId: 'com.example.incidentResposneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaWGT8VllVaNG4NcEeGyrNAY0OD9lhIJs',
    appId: '1:94237990307:web:aa4b9770e8334068a44e16',
    messagingSenderId: '94237990307',
    projectId: 'rapid-report-bdfe6',
    authDomain: 'rapid-report-bdfe6.firebaseapp.com',
    storageBucket: 'rapid-report-bdfe6.firebasestorage.app',
    measurementId: 'G-0D0V1WK91N',
  );

}